### ISSUE TITLE
Using this workshop with io.js

### ISSUE THREAD

**Issue by ghost** [isRuslan/learn-generators#12]
Hi. I have installed io.js 1.1.0 and when i tried to execute `$ learn-generators` i got an error: <pre>You need nodejs >= 0.11.x or iojs >= 1.0.x</pre>
`io.js` was installed globally.

**Comment by isRuslan** [comment]
Hi, Can you please provide terminal output for `node -v` or `iojs -v` commands to check that iojs was installed properly?
Works for me with iojs@1.1.0

![iojs-gen](https://cloud.githubusercontent.com/assets/2136166/6153414/7994dbde-b235-11e4-99df-e9aa3f7d2b58.jpg)

**Comment by ghost** [comment]
It was because i had an old version of node - 0.10.36. I was confused by `"or"` in console.error message and i thought that it checks `node -v` or `iojs -v`

**Comment by isRuslan** [comment]
Glad we solved that. I'll improve error message.

**Comment by jtpio** [comment]
Hi,

I have the same problem with node.js v0.10.36 and io.js v3.0.0.
![node_iojs_versions](https://cloud.githubusercontent.com/assets/591645/9170505/cdbf052a-3f63-11e5-933c-43eb3200d102.png)

Both node.js and io.js are installed on the same machine but I need to keep node v0.10.36.
Is there a way to specifically run `learn-generators` with io.js?

**Comment by isRuslan** [comment]
Hi @jtpio, currently `learn-generators` cannot recognize whenever **node.js** or **io.js** is installed on you machine, it is always try to invoke `node [--harmony] learn-generators.js`. 

But you can use it with **io.js** by running `learn-generators.js` directly with `iojs` command.

Globally installed:

```
$ npm install learn-generators -g
$ iojs /usr/local/lib/node_modules/learn-generators/learn-generators.js
```

Locally installed:

```
$ npm install learn-generators
$ cd $_
$ iojs learn-generators
```

It is **really** tricky and need always invoke `iojs learn-generators [arguments]` to get work done.
But in your situation this is the fastest way.

**Comment by jtpio** [comment]
Thanks for the trick, it does the job.
