### ISSUE TITLE
cannot find module ./learn-generators.js

### ISSUE THREAD

**Issue by ahdinosaur** [isRuslan/learn-generators#16]
> $ npm i -g learn-generators
> /home/michael/.nvm/versions/io.js/v1.3.0/bin/learn-generators -> /home/michael/.nvm/versions/io.js/v1.3.0/lib/node_modules/learn-generators/start
> learn-generators@1.2.4 /home/michael/.nvm/versions/io.js/v1.3.0/lib/node_modules/learn-generators
> ├── has-generators@1.0.1
> ├── colors-tmpl@1.0.0 (colors@1.0.3)
> ├── workshopper-wrappedexec@0.1.2 (after@0.8.1, xtend@2.1.2)
> ├── workshopper-exercise@2.3.0 (after@0.8.1, visualwidth@0.0.1, xtend@2.1.2, tuple-stream@0.0.2, split@0.3.3, chalk@0.4.0, through2@0.4.2, i18n-core@1.3.2)
> └── workshopper@2.3.1 (map-async@0.1.1, xtend@3.0.0, mkdirp@0.3.5, visualwidth@0.0.1, colors-tmpl@0.1.1, optimist@0.6.1, chalk@0.4.0, terminal-menu@1.0.2, i18n-core@1.3.2, msee@0.1.1)
> 
> $ learn-generators
> module.js:322
>     throw err;
>           ^
> Error: Cannot find module '/home/michael/repos/nodeschool/learn-generators/learn-generators.js'
>     at Function.Module._resolveFilename (module.js:320:15)
>     at Function.Module._load (module.js:262:25)
>     at Function.Module.runMain (module.js:485:10)
>     at startup (node.js:111:16)
>     at node.js:799:3

**Comment by isRuslan** [comment]
Oh yes, should be fixed in `1.2.5`, try update the package. Thanks!

**Comment by ahdinosaur** [comment]
sweet, works now. :cake:
