### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by borisschapira** [isRuslan/learn-generators#18]
Everything is in the title :wink: : the current version is fully developed around bash.exe, not available on Windows. Is it possible to make the project shell-agnostic, to make it work on alternative shells or non-Unix system ?

**Comment by isRuslan** [comment]
Yes, try to update to `1.3.1` version.
@julien-f made some work in #19 to remove the need for bash.

**Comment by julien-f** [comment]
@borisschapira Is this still an issue?

**Comment by borisschapira** [comment]
Nope, now it works :+1:

**Comment by julien-f** [comment]
Good :)

Thanks for the feedback.
