### ISSUE TITLE
help doesn't render correctly

### ISSUE THREAD

**Issue by max-mapper** [isRuslan/learn-generators#3]
When I select help from the main menu I get this:

![screen shot 2015-01-24 at 1 52 00 pm](https://cloud.githubusercontent.com/assets/39759/5889194/3474ca6e-a3d0-11e4-8797-98f28240214c.png)

**Comment by isRuslan** [comment]
Seems like `workshopper` didn't recognize `colors-tmpl` package.
Now should be fixed. Try update package. Thanks.
