### ISSUE TITLE
Help with "Look Sync. Do Async"

### ISSUE THREAD

**Issue by swinston100** [isRuslan/learn-generators#30]
Hi 

Thanks for the great tutorials.

As suggested I added some `console.log` statements to try and understand the program flow in your example.

``` js
var fs = require('fs');

function run (generator) {
  console.log('before it');
  var it = generator(go);
  console.log('after it');
  function go (err, result) {
    console.log('before next');
    it.next(result);
    console.log('after next');
  }
  console.log('before go');

  go();
  console.log('after go');

}

run(function* (done) {
  // read `learn-generators` exercises folder
  console.log('before yield');
  var exercises = yield fs.readdir('exercises', done);
  console.log('after yield');

  console.log(exercises); // [ 'look_sync_do_async', ..., 'run_stop_run' ]
});

```

With the following output:

> before it
> after it
> before go
> before next
> before yield
> after next
> after go *
> before next
> after yield
> RESULTS
> after next

I am somewhat lacking in my understanding of generators as I can't understand how the program get's back to "before next" after "after go" (see \* above). What happens that causes the go function to be called again?

Thanks for you help

Steven

**Comment by isRuslan** [comment]
Hi @swinston100 thanks for reasonable question, here is my attempt to clarify this.
**go()** function is actually called **twice** here:
- first time **to start** generator:

``` js
// inside run()
var it = generator(go); // push inside generator our go()

console.log('before go');

go();
console.log('after go');
```

`it.next(result)` is running our generator with empty `result` (try to log `result` too);
- second time **to wait** until fs.readdir finished:

``` js
/* it executes done() which is our go() with non-empty result */
yield fs.readdir('exercises', done); 
```

# 

If you try to log inner `result` argument you get something like this:

``` js
var fs = require('fs');

function run (generator) {
  console.log('before it');
  var it = generator(go);
  console.log('after it');
  function go (err, result) {
    console.log('before next');
    console.log('INNER_RESULT', result);
    it.next(result);
    console.log('after next');
  }
  console.log('before go');

  go();
  console.log('after go');

}

run(function* (done) {
  console.log('before yield');
  var exercises = yield fs.readdir('exercises', done);
  console.log('after yield');

  console.log(exercises);
});
```

> before it
> after it
> before go
> before next
> INNER_RESULT undefined // generator started
> before yield
> after next
> after go
> before next
> INNER_RESULT [ 'catch_error', ... ]
> after yield
> [ 'catch_error', ..]
> after next

**Comment by swinston100** [comment]
Thanks for the super-speedy response!
I think the part of my understanding I was missing was that on competition of the async function, `done()` is actually in turn calling `go()` with non-empty result. This is because we "pushed the go function" into the generator.
Maybe not worded so well but it helps me understand - feel free to phrase more technically!

**Comment by isRuslan** [comment]
Hope this helps :)
