### ISSUE TITLE
Question: Look sync, make promise

### ISSUE THREAD

**Issue by rob-yoti** [isRuslan/learn-generators#34]
As part of my working solution, I wrote the code:
`if (result.done) result.return(result.value);`

The official solution is:
`if (result.done) return result.value;`

Are both acceptable, or should I have not used `Generator.prototype.return()` in this instance?

Thanks in advance!

**Comment by isRuslan** [comment]
Hi @rob-yoti! Yes, both samples are possible, good point to mark, thanks!
In solution `if (result.done) result.return(result.value);` is used for readability only - shows that you actually exiting `go()` function.
`Generator.prototype.return` will terminate generator (`result`) in our case and will do the job too, so you can use whenever you prefer.

**Comment by isRuslan** [comment]
published comment in `learn-generators@1.7.1` 👍
