### ISSUE TITLE
Exercise 3 is confusing

### ISSUE THREAD

**Issue by tamzinblake** [isRuslan/learn-generators#35]
The entire description of delegating generators:

```
We can delegate iteration control from our generator to another one.
yield * expression will do the trick, * means that expression
is a generator too, so we can send message to it.
```

It doesn't explain what "delegate iteration control" means or what I should expect to happen when we "send message" to another generator.

**Comment by isRuslan** [comment]
Hi @thomblake, thank you for feedback and can you explain what did exactly you stuck with? 
> what I should expect to happen when we "send message" to another generator

when you send message from your **outer** generator  to **inner** generator - you give all flow control you it (**inner** one), it means that caller of **outer** will get all the values from **inner** and paused when inner yielded.
