### ISSUE TITLE
Incorrect expected result for "generator iterator"

### ISSUE THREAD

**Issue by chikh** [isRuslan/learn-generators#5]
Factorial's expected output is "1, 5, 20, 60, 120", but actually it must be "1, 1, 2, 6, 24, 120". See http://en.wikipedia.org/wiki/Factorial

**Comment by isRuslan** [comment]
A little misunderstanding.

Iterate over `5!` means:
step_1 = **1** = 1
step_2 = **5** \* step_1 // **5** \* 1 = 5
step_3 = **4** \* step_2 // **4** \* 5 \* 1 = 20
step_4 = **3** \* step_3  // **3** \* 4 \* 5 \* 1 = 60
step_5 = **2** \* step_4 // **2** \* 3 \* 4 \* 5 \* 1 = 120

And dosen't means: n! **!=** 1! + 2! + ... n-1!

The task probably need better description.

**Comment by chikh** [comment]
Oh, I see. Then yes, surely description needs more clarification. But it's another issue.
