### ISSUE TITLE
Generators and Iterators - wrong task goal

### ISSUE THREAD

**Issue by floatdrop** [isRuslan/learn-generators#7]
As task says:

> Write a generator function factorial that, given an input number, starts at 1 and goes
> up to the number, yielding the factorial of each number along the way.

So, what I expect to do is:

> factorial(5):
> 1! = 1
> 2! = 2
> 3! = 6
> 4! = 24
> 5! = 120

But answer is wrong, because what seems to be checked is:

> Write a generator function factorial that, given an input number, yielding the intermediate steps of factorial computation.

Should it be corrected in some way?

**Comment by isRuslan** [comment]
isRuslan/learn-generators#5

Yes, need to correct that way. Agreed.

**Comment by isRuslan** [comment]
Seems to be better if `factorial` will actually yield factorial of each number from `[1..n]` sequence.
Especially since it is written in the task :)
Will fixed in 1.2.0.

**Comment by floatdrop** [comment]
@isRuslan yep. Thanks! :star2:
